{"id":310337720,"node_id":"MDEwOlJlcG9zaXRvcnkzMTAzMzc3MjA=","name":"python-vulnerable","full_name":"Serubin/python-vulnerable","private":false,"owner":{"login":"Serubin","id":1234465,"node_id":"MDQ6VXNlcjEyMzQ0NjU=","avatar_url":"https://avatars.githubusercontent.com/u/1234465?v=4","gravatar_id":"","url":"https://api.github.com/users/Serubin","html_url":"https://github.com/Serubin","followers_url":"https://api.github.com/users/Serubin/followers","following_url":"https://api.github.com/users/Serubin/following{/other_user}","gists_url":"https://api.github.com/users/Serubin/gists{/gist_id}","starred_url":"https://api.github.com/users/Serubin/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Serubin/subscriptions","organizations_url":"https://api.github.com/users/Serubin/orgs","repos_url":"https://api.github.com/users/Serubin/repos","events_url":"https://api.github.com/users/Serubin/events{/privacy}","received_events_url":"https://api.github.com/users/Serubin/received_events","type":"User","site_admin":false},"html_url":"https://github.com/Serubin/python-vulnerable","description":null,"fork":false,"url":"https://api.github.com/repos/Serubin/python-vulnerable","forks_url":"https://api.github.com/repos/Serubin/python-vulnerable/forks","keys_url":"https://api.github.com/repos/Serubin/python-vulnerable/keys{/key_id}","collaborators_url":"https://api.github.com/repos/Serubin/python-vulnerable/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/Serubin/python-vulnerable/teams","hooks_url":"https://api.github.com/repos/Serubin/python-vulnerable/hooks","issue_events_url":"https://api.github.com/repos/Serubin/python-vulnerable/issues/events{/number}","events_url":"https://api.github.com/repos/Serubin/python-vulnerable/events","assignees_url":"https://api.github.com/repos/Serubin/python-vulnerable/assignees{/user}","branches_url":"https://api.github.com/repos/Serubin/python-vulnerable/branches{/branch}","tags_url":"https://api.github.com/repos/Serubin/python-vulnerable/tags","blobs_url":"https://api.github.com/repos/Serubin/python-vulnerable/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/Serubin/python-vulnerable/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/Serubin/python-vulnerable/git/refs{/sha}","trees_url":"https://api.github.com/repos/Serubin/python-vulnerable/git/trees{/sha}","statuses_url":"https://api.github.com/repos/Serubin/python-vulnerable/statuses/{sha}","languages_url":"https://api.github.com/repos/Serubin/python-vulnerable/languages","stargazers_url":"https://api.github.com/repos/Serubin/python-vulnerable/stargazers","contributors_url":"https://api.github.com/repos/Serubin/python-vulnerable/contributors","subscribers_url":"https://api.github.com/repos/Serubin/python-vulnerable/subscribers","subscription_url":"https://api.github.com/repos/Serubin/python-vulnerable/subscription","commits_url":"https://api.github.com/repos/Serubin/python-vulnerable/commits{/sha}","git_commits_url":"https://api.github.com/repos/Serubin/python-vulnerable/git/commits{/sha}","comments_url":"https://api.github.com/repos/Serubin/python-vulnerable/comments{/number}","issue_comment_url":"https://api.github.com/repos/Serubin/python-vulnerable/issues/comments{/number}","contents_url":"https://api.github.com/repos/Serubin/python-vulnerable/contents/{+path}","compare_url":"https://api.github.com/repos/Serubin/python-vulnerable/compare/{base}...{head}","merges_url":"https://api.github.com/repos/Serubin/python-vulnerable/merges","archive_url":"https://api.github.com/repos/Serubin/python-vulnerable/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/Serubin/python-vulnerable/downloads","issues_url":"https://api.github.com/repos/Serubin/python-vulnerable/issues{/number}","pulls_url":"https://api.github.com/repos/Serubin/python-vulnerable/pulls{/number}","milestones_url":"https://api.github.com/repos/Serubin/python-vulnerable/milestones{/number}","notifications_url":"https://api.github.com/repos/Serubin/python-vulnerable/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/Serubin/python-vulnerable/labels{/name}","releases_url":"https://api.github.com/repos/Serubin/python-vulnerable/releases{/id}","deployments_url":"https://api.github.com/repos/Serubin/python-vulnerable/deployments","created_at":"2020-11-05T15:17:06Z","updated_at":"2020-11-05T15:56:03Z","pushed_at":"2021-10-01T05:55:16Z","git_url":"git://github.com/Serubin/python-vulnerable.git","ssh_url":"git@github.com:Serubin/python-vulnerable.git","clone_url":"https://github.com/Serubin/python-vulnerable.git","svn_url":"https://github.com/Serubin/python-vulnerable","homepage":null,"size":4,"stargazers_count":0,"watchers_count":0,"language":"Dockerfile","has_issues":true,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":false,"forks_count":0,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":5,"license":null,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"open_issues":5,"watchers":0,"default_branch":"master","permissions":{"admin":false,"maintain":false,"push":false,"triage":false,"pull":true},"temp_clone_token":"","network_count":0,"subscribers_count":1}